//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace midtermproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessory
    {
        public int id { get; set; }
        public string AccessoryCode { get; set; }
        public string Accessory1 { get; set; }
        public string AccessoryMaterial { get; set; }
        public string Price { get; set; }
        public string ShippingTime { get; set; }
    }
}
